# This is a sample build configuration for other languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: coders51/elixir-postgres

pipelines:
  default:
    - step:
        script:
          - /etc/init.d/postgresql start # starting the service
          - sudo -u postgres sh -c 'createuser postgres' # creating a postgres user
          - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
