image: bitwalker/alpine-elixir-phoenix:latest
pipelines:
  branches:
    develop:
      - step:
          caches:
            - deps
            - nodewrapper
          script:
            - MIX_ENV=test mix deps.get
            - MIX_ENV=test mix ecto.create
            - MIX_ENV=test mix ecto.migrate
            - mix test
          services:
            - database

definitions:
  caches:
    deps: deps
    nodewrapper: apps/wsdjs_web/assets/node_modules
  services:
    database:
      image: postgres:9.6
      environment:
        POSTGRES_PASSWORD: postgres