# Since configuration is shared in umbrella projects, this file
# should only configure the :wsdjs_proxy application itself
# and only for organization purposes. All other config goes to
# the umbrella root.
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :wsdjs_proxy, WsdjsProxy.Endpoint,
  http: [port: 6000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

config :master_proxy,
  http: [:inet6, port: 4080],
  backends: [
    %{
      host: ~r/localhost/,
      path: ~r/api/,
      phoenix_endpoint: WsdjsApi.Endpoint
    },
    %{
      host: ~r/localhost/,
      phoenix_endpoint: WsdjsWeb.Endpoint
    },
    %{
      verb: ~r/get/i,
      path: ~r{^/master-proxy-plug-test$},
      plug: MasterProxy.Plug.Test,
      opts: [1, 2, 3]
    }
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.
